name: Continuous Training
on:
  push:
    branches:
      - prueba-coment
  workflow_dispatch:
    inputs:
      reason:
        description: Motivo de la corrida
        required: false
        default: running CT

jobs:
  continuous-training:
    runs-on: ubuntu-latest
    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Acceso al repositorio
        uses: actions/checkout@v3

      - name: Actualizar a Node16
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Creando y activando un entorno virtual
        run: |
           pip3 install virtualenv
           virtualenv venv
           source venv/bin/activate
           git pull           
           
      - name: Actualizando el archivo
        run: |
           python utils.py
    
      - name: Commit y push de los cambios en el archivo .dvc 
        run: |
          git config --local user.email "ignacio_m_16@hotmail.com"
          git config --local user.name "github-actions[bot]"
          git add report.txt
          git commit -m "Ultimo update?"
          git push

      - uses: iterative/setup-cml@v1
      - name: Agregado comentario con el reporte
        run: |
          git checkout HEAD
          cat report.txt >> report.md 
          cml comment create report.md 
        # --target=commit/355d689
         
