name: Continuous Training
on:
  push:
    branches:
      - prueba-coment

jobs:
  continuous-training:
    runs-on: ubuntu-latest
    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Acceso al repositorio
        uses: actions/checkout@v3